<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="body_macro" params="suffix parent wheel_radius wheel_base vehicle_mass vehicle_mass_height vehicle_width vehicle_length vehicle_height">
  <xacro:property name="pi" value="3.1415926835897931" />
    <joint name="${suffix}_joint" type="fixed">
      <parent link="${parent}"/>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_radius}"/>
      <child  link="${suffix}_link"/>
    </joint>  
    <link name="${suffix}_link">
      <inertial>
        <origin xyz="${wheel_base/2} 0 0" rpy="0 0 0"/>
        <mass value="${vehicle_mass}"/>
        <inertia ixx="${(vehicle_width*vehicle_width+vehicle_mass_height*vehicle_mass_height)*vehicle_mass/12.0}" ixy="0.0" ixz="0.0" 
                 iyy="${(vehicle_length*vehicle_length+vehicle_mass_height*vehicle_mass_height)*vehicle_mass/12.0}" iyz="0.0" 
                 izz="${(vehicle_width*vehicle_width+vehicle_length*vehicle_length)*vehicle_mass/12.0}"/>
      </inertial>
      <visual>
        <origin xyz="0.025 -0.01 -0.085" rpy="1.570796 0 1.5707963"/>
        <geometry>
          <mesh filename="package://vehicle_model/mesh/car_fifthwheel.dae" scale="1 1 1"/>
        </geometry>
        <material name="black">
            <color rgba="${25/255} ${25/255} ${25/255} .9"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${wheel_base/2} 0 ${vehicle_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${vehicle_length} ${vehicle_width} ${vehicle_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${suffix}_5whl_joint1" type="fixed">
      <origin xyz="0.125 0 0.145" rpy="0 0 0" />
      <parent link="${parent}"/>
      <child  link="${suffix}_5whl"/>
    </joint>  
    <link name="${suffix}_5whl">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
                 iyy="0.001" iyz="0.0" 
                 izz="0.001"/>
      </inertial>
      <visual>
        <geometry><box size="0.024 0.024 0.024"/></geometry>
        <material name="black">
          <color rgba="${25/255} ${25/255} ${25/255} .9"/>
        </material>
      </visual>
      <collision name="5whl_collision">
        <geometry><box size="0.024 0.024 0.024"/></geometry>
      </collision>

    <sensor name='5whl_sensor' type='contact'>
        <pose frame=''>0 0 0.4075  0 0 0</pose>
        <always_on>1</always_on>
        <contact>
          <collision>5whl_collision</collision>
          <topic>__default_topic__</topic>
        </contact>
        <plugin name='contact_sensor_plugin' filename='libgazebo_ros_bumper.so'>
          <bumperTopicName>5whl_contact</bumperTopicName>
          <frameName>5whl</frameName>
        </plugin>
      </sensor>
    </link>
    <joint name="${suffix}_5whl_joint2" type="fixed">
      <origin xyz="0.09 -0.022 0" rpy="0 0 0.2617994" />
      <parent link="${suffix}_5whl"/>
      <child  link="${suffix}_5whl2"/>
    </joint>  

    <link name="${suffix}_5whl2">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
                 iyy="0.001" iyz="0.0" 
                 izz="0.001"/>
      </inertial>
      <visual>
        <geometry><box size="0.05 0.01 0.024"/></geometry>
        <material name="black"><color rgba="0 0 0 .9"/></material>
      </visual>
      <collision>
        <geometry><box size="0.05 0.01 0.024"/></geometry>
      </collision>
    </link>

    <joint name="${suffix}_5whl_joint3" type="fixed">
      <origin xyz="0.09 0.022 0" rpy="0 0 -0.2617994" />
      <parent link="${suffix}_5whl"/>
      <child  link="${suffix}_5whl3"/>
    </joint>
    <link name="${suffix}_5whl3">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
                 iyy="0.001" iyz="0.0" 
                 izz="0.001"/>
      </inertial>
      <visual>
        <geometry><box size="0.05 0.01 0.024"/></geometry>
        <material name="black"><color rgba="0 0 0 .9"/></material>
      </visual>
      <collision>
        <geometry><box size="0.05 0.01 0.024"/></geometry>
      </collision>
    </link>

    <joint name="${suffix}_L_fender_joint" type="fixed">
      <origin xyz="-0.06 0.09 0.08" rpy="1.5707963 0 0"/>
      <parent link="${parent}"/>
      <child  link="${suffix}_L_fender"/>
    </joint>  
    <link name="${suffix}_L_fender">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
                 iyy="0.01" iyz="0.0" 
                 izz="0.01"/>
      </inertial>
      <visual>
        <geometry><cylinder radius="0.005" length="0.14"/></geometry>
        <material name="black"><color rgba="0 0 0 .9"/></material>
      </visual>
      <collision name="L_fender_collision">
        <geometry><cylinder radius="0.005" length="0.14"/></geometry>
      </collision>

      <sensor name='L_fender_sensor' type='contact'>
        <always_on>1</always_on>
        <contact>
          <collision>L_fender_collision</collision>
          <topic>__default_topic__</topic>
        </contact>
        <plugin name='L_fender_contact_sensor_plugin' filename='libgazebo_ros_bumper.so'>
          <bumperTopicName>L_fender_contact</bumperTopicName>
          <frameName>L_fender</frameName>
        </plugin>
      </sensor>
    </link>

    <joint name="${suffix}_R_fender_joint" type="fixed">
      <origin xyz="-0.06 -0.09 0.08" rpy="1.5707963 0 0"/>
      <parent link="${parent}"/>
      <child  link="${suffix}_R_fender"/>
    </joint>  
    <link name="${suffix}_R_fender">
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
                 iyy="0.01" iyz="0.0" 
                 izz="0.01"/>
      </inertial>
      <visual>
        <geometry><cylinder radius="0.005" length="0.14"/></geometry>
        <material name="black"><color rgba="0 0 0 .9"/></material>
      </visual>
      <collision name="R_fender_collision">
        <geometry><cylinder radius="0.005" length="0.14"/></geometry>
      </collision>

      <sensor name='R_fender_sensor' type='contact'>
        <always_on>1</always_on>
        <contact>
          <collision>R_fender_collision</collision>
          <topic>__default_topic__</topic>
        </contact>
        <plugin name='R_fender_contact_sensor_plugin' filename='libgazebo_ros_bumper.so'>
          <bumperTopicName>R_fender_contact</bumperTopicName>
          <frameName>R_fender</frameName>
        </plugin>
      </sensor>
    </link>

    <light name='under' type='directional'>
      <cast_shadows>1</cast_shadows>
      <pose relative_to="base_link">0 0 0  0 0 0</pose>
      <diffuse>1 1 1 1</diffuse>
      <specular>0.1 0.1 0.1 1</specular>
      <attenuation>
        <range>1</range>
        <constant>0</constant>
        <linear>0.9</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>0 0 1</direction>
    </light>
  </xacro:macro>  
</robot>
