# Upward facing camera, during docking
base_link2camera:
  x: -1
  y: 0
  z: 0.0
  roll: 0.0
  pitch: -1.570795
  yaw: 0
base_link2imu:
  x: 0.0
  y: 0.0
  z: 0.01
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
base_link2quad:
  x: 0.31
  y: 0.07
  z: 0.1
  roll: 0.0
  pitch: 0.0
  yaw: 0
