joint_state_controller:
  # reads all joint positions and publish them on to "/joint_states".
  # This controller does not send any command to the actuators
  type: joint_state_controller/JointStateController
  publish_rate: 50  

steering_left_front_position_controller:
  type: position_controllers/JointPositionController
  joint: steering_left_front_joint
  # The input position value is simply forwarded as output command
  # to the joint actuator. The values of P, I and D have no effect
steering_right_front_position_controller:
  type: position_controllers/JointPositionController
  joint: steering_right_front_joint

wheel_left_front_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_left_front_joint
  #The input velocity value is simply forwarded as output command
  # to the joint actuator. The values of P, I and D have no effect
wheel_right_front_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: wheel_right_front_joint
