# Check "truck_mo" file in Fusion360
footprint: # legacy
  [[0.377, 0.255],
  [0.177, 0.255],
  [0.177, 0.165],
  [-0.076, 0.165],
  [-0.076, -0.165],
  [0.177, -0.165],
  [0.177, -0.255],
  [0.377, -0.255]]

path:
  safe_distance: 0.04 # [m] insist on minimum distance
  # the truck chassis can be considered to consist of 2 rectangles,
  # (with 0,0 being the base_link):
  # min (-0.076, -0.165) max (0.177, +0.165)
  # min (+0.177, -0.255) max (0.377, +0.255)
  chassis_front:
    [[0.377, 0.255],
    [0.177, 0.255],
    [0.177, -0.255],
    [0.377, -0.255]]
  chassis_back:
    [[0.177, 0.165],
    [-0.076, 0.165],
    [-0.076, -0.165],
    [0.177, -0.165]]

  kappa_max: 1.48 # [1/m]
  sigma_max: 8.6 # [1/m^2]; want more responsive steering

  # Check "Vehicle Teleoperation Weekly Meeting_20210910.pptx"
  wheel_base:   0.267  # [m]
  track_width:  0.484  # [m]
  wheel_radius: 0.060  # [m]
  wheel_width:  0.042  # [m]
  rear_track_width: 0.303  # [m]

  controller: {k1: 1.5, k2: 0.25, k3: 1.0}

  motion_noise: {alpha1: 0.1,  alpha2: 0.05, alpha3: 0.05, alpha4: 0.2}

  measurement_noise:
    std_x:     0.1     # [m]
    std_y:     0.1     # [m]
    std_theta: 0.05    # [rad]
